// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user/user.proto

package userv1beta1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// A user's information.
type User struct {
	// A user's ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// An email address.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// A username.
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// A display name.
	DisplayName          string   `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "user.v1beta1.User")
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74) }

var fileDescriptor_ed89022014131a74 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2d, 0x4e, 0x2d,
	0xd2, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x3c, 0x60, 0x76, 0x99, 0x61, 0x52,
	0x6a, 0x49, 0xa2, 0xa1, 0x52, 0x36, 0x17, 0x4b, 0x68, 0x71, 0x6a, 0x91, 0x10, 0x1f, 0x17, 0x53,
	0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x08, 0x17, 0x6b,
	0x6a, 0x6e, 0x62, 0x66, 0x8e, 0x04, 0x13, 0x58, 0x08, 0xc2, 0x11, 0x92, 0xe2, 0xe2, 0x00, 0xe9,
	0xce, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x06, 0x4b, 0xc0, 0xf9, 0x42, 0x8a, 0x5c, 0x3c, 0x29, 0x99,
	0xc5, 0x05, 0x39, 0x89, 0x95, 0xf1, 0x60, 0x79, 0x16, 0xb0, 0x3c, 0x37, 0x54, 0xcc, 0x2f, 0x31,
	0x37, 0xd5, 0x29, 0x80, 0x4b, 0x20, 0x39, 0x3f, 0x57, 0x0f, 0xd9, 0x01, 0x4e, 0x9c, 0x20, 0xeb,
	0x03, 0x40, 0x2e, 0x0b, 0x60, 0x8c, 0xe2, 0x06, 0x49, 0x41, 0x65, 0x16, 0x31, 0x31, 0x87, 0x46,
	0x44, 0xac, 0x62, 0xe2, 0x01, 0x29, 0xd0, 0x0b, 0x33, 0x74, 0x02, 0x09, 0x9e, 0x82, 0x70, 0x63,
	0xa0, 0xdc, 0x24, 0x36, 0xb0, 0x9f, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x14, 0xa3, 0x60,
	0xe3, 0xe6, 0x00, 0x00, 0x00,
}
